import {env} from '../../config/env.js';import {createKeyPool} from '../key-pool.js';
const RETRYABLE=new Set([401,403,408,409,425,429,500,502,503,504]);
const err=(message,status)=>Object.assign(new Error(message),{status,code:status===429?'RATE_LIMIT':'PROVIDER'});
async function postJson(url,headers,body){const c=new AbortController(),t=setTimeout(()=>c.abort(),120000);try{const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(body),signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw err(`Video provider HTTP ${r.status}`,r.status);return d}catch(e){if(e?.name==='AbortError')throw Object.assign(new Error('Video provider request timed out'),{code:'TIMEOUT',retryable:true});throw e}finally{clearTimeout(t)}}
const promptFor=i=>String(i?.prompt||i?.text||i?.description||i?.scene||i?.title||JSON.stringify(i)).slice(0,8000);
async function lumaGenerate(key,url,model,input){const result=await postJson(url,{'Authorization':`Bearer ${key}`,'Content-Type':'application/json'},{prompt:promptFor(input),model,aspect_ratio:input?.aspect_ratio||'9:16',duration:String(input?.duration||5)});if(result?.assets?.video||result?.video?.url||result?.url)return result;const id=result?.id;if(!id)return result;for(let attempt=0;attempt<30;attempt++){await new Promise(r=>setTimeout(r,4000));const r=await fetch(`${url.replace(/\/$/,'')}/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${key}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw err(`Video provider status HTTP ${r.status}`,r.status);if(d?.state==='failed'||d?.status==='failed')throw Object.assign(new Error(d?.failure_reason||'Video generation failed'),{code:'PROVIDER'});if(d?.assets?.video||d?.video?.url||d?.url)return d}throw Object.assign(new Error('Video generation timed out waiting for provider'),{code:'TIMEOUT',retryable:true})}
function lumaProvider(keys,url,model){const pool=createKeyPool(keys);return {async generate(input){if(!pool.size)throw Object.assign(new Error('Luma credentials missing'),{code:'CONFIGURATION'});return pool.run(key=>lumaGenerate(key,url,model,input))}}}
function falProvider(keys,url,model){const pool=createKeyPool(keys);return {async generate(input){if(!pool.size)throw Object.assign(new Error('FAL credentials missing'),{code:'CONFIGURATION'});return pool.run(key=>postJson(url,{'Authorization':`Key ${key}`,'Content-Type':'application/json'},{...input,prompt:promptFor(input),model:model||undefined}))}}}
export function createVideoProvider(){const e=env(),luma=e.PROVIDER_KEYS?.luma||[],fal=e.PROVIDER_KEYS?.fal||[],lumaUrl=e.LUMA_API_URL||'https://api.lumalabs.ai/dream-machine/v1/generations',falModel=e.FAL_VIDEO_MODEL||'',falUrl=e.FAL_VIDEO_API_URL||(falModel?`https://fal.run/${falModel}`:'');const providers=[];if(luma.length)providers.push(lumaProvider(luma,lumaUrl,e.LUMA_VIDEO_MODEL||'ray-2'));if(fal.length&&falUrl)providers.push(falProvider(fal,falUrl,falModel));return {async generate(input){let last;for(const provider of providers){try{return await provider.generate(input)}catch(e){last=e;if(!(e?.retryable||RETRYABLE.has(e?.status)))throw e}}throw last||Object.assign(new Error('Video provider not configured'),{code:'CONFIGURATION'})}}}
