const send=(res,status,data)=>{res.statusCode=status;res.setHeader('content-type','application/json');res.end(JSON.stringify(data))};
const read=async req=>{let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};
const call=async(req,path,method='GET',body)=>{const a=req.headers.authorization;if(!a?.startsWith('Bearer '))throw Object.assign(new Error('Authentication required'),{status:401});const r=await fetch(`http://127.0.0.1:${process.env.PORT||10000}${path}`,{method,headers:{authorization:a,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}};if(!r.ok)throw Object.assign(new Error(d?.error?.message||`API ${r.status}`),{status:r.status});return d};
const tools=[
{name:'list_channels',description:'List YouTube channels.',inputSchema:{type:'object',properties:{}}},
{name:'list_projects',description:'List automation projects.',inputSchema:{type:'object',properties:{}}},
{name:'start_project',description:'Start a project pipeline.',inputSchema:{type:'object',properties:{project_id:{type:'string'}},required:['project_id']}},
{name:'get_job_status',description:'Get job status.',inputSchema:{type:'object',properties:{job_id:{type:'string'}},required:['job_id']}},
{name:'get_pipeline_status',description:'Get pipeline status.',inputSchema:{type:'object',properties:{pipeline_run_id:{type:'string'}},required:['pipeline_run_id']}},
{name:'retry_job',description:'Retry a failed job.',inputSchema:{type:'object',properties:{job_id:{type:'string'}},required:['job_id']}},
{name:'create_schedule',description:'Schedule a project.',inputSchema:{type:'object',properties:{name:{type:'string'},channel_id:{type:'string'},project_id:{type:'string'},publish_at:{type:'string'},timezone:{type:'string'},schedule_type:{type:'string'},cron_expression:{type:'string'},payload:{type:'object'},enabled:{type:'boolean'}},required:['project_id','publish_at']}},
{name:'channel_analytics',description:'Read channel analytics.',inputSchema:{type:'object',properties:{channel_id:{type:'string'}}}},
{name:'list_memory',description:'Read channel/project memory.',inputSchema:{type:'object',properties:{}}}
];
async function tool(req,n,a){switch(n){case'list_channels':return call(req,'/api/channels');case'list_projects':return call(req,'/api/projects');case'start_project':return call(req,`/api/projects/${encodeURIComponent(a.project_id)}/run`,'POST',{});case'get_job_status':return call(req,`/api/jobs/${encodeURIComponent(a.job_id)}`);case'get_pipeline_status':return call(req,`/api/pipeline/runs/${encodeURIComponent(a.pipeline_run_id)}`);case'retry_job':return call(req,`/api/jobs/${encodeURIComponent(a.job_id)}`,'POST',{command:'RETRY'});case'create_schedule':return call(req,'/api/schedules','POST',a);case'channel_analytics':return call(req,`/api/analytics/channels${a.channel_id?`?channel_id=${encodeURIComponent(a.channel_id)}`:''}`);case'list_memory':return call(req,'/api/memory');default:throw Object.assign(new Error('Unknown tool'),{status:400})}}
export async function handleMcp(req,res){try{const b=await read(req),id=b.id??null;if(b.method==='initialize')return send(res,200,{jsonrpc:'2.0',id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'youtube-automation',version:'1.0.0'}}});if(b.method==='notifications/initialized')return res.writeHead(202).end();if(b.method==='ping')return send(res,200,{jsonrpc:'2.0',id,result:{}});if(b.method==='tools/list')return send(res,200,{jsonrpc:'2.0',id,result:{tools}});if(b.method==='tools/call'){const d=await tool(req,b.params?.name,b.params?.arguments||{});return send(res,200,{jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(d)}],structuredContent:d}})}return send(res,200,{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}})}catch(e){return send(res,e.status||500,{jsonrpc:'2.0',id:null,error:{code:-32000,message:e.message||'Internal error'}})}}
