import {schedules} from '../../database/repositories/schedule.repository.js';
import {enqueue} from '../../queue/queue.service.js';
import {nextCron} from '../../scheduler/scheduler.js';
const send=(res,status,data)=>{res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(data))};
export async function list(req,res){try{send(res,200,{success:true,data:await schedules.list(req.user.id)})}catch(error){console.error('schedules.list failed',error);send(res,500,{success:false,error:{code:'DATABASE',message:'Schedules could not be loaded'}})}}
export async function get(req,res){try{const data=await schedules.get(req.params.id,req.user.id);if(!data)return send(res,404,{success:false,error:{code:'NOT_FOUND',message:'Schedule not found'}});send(res,200,{success:true,data})}catch(error){send(res,500,{success:false,error:{code:'DATABASE',message:'Schedule could not be loaded'}})}}
export async function create(req,res){try{const body=req.body||{};if(body.schedule_type==='cron')nextCron(new Date(body.publish_at),body.cron_expression,body.timezone||'UTC');const data=await schedules.create({userId:req.user.id,name:body.name,channelId:body.channel_id,projectId:body.project_id,publishAt:body.publish_at,timezone:body.timezone||'UTC',scheduleType:body.schedule_type||'once',cronExpression:body.cron_expression,payload:body.payload,enabled:body.enabled!==false});send(res,201,{success:true,data})}catch(error){send(res,400,{success:false,error:{code:'INVALID_SCHEDULE',message:error.message}})}}
export async function update(req,res){try{const body=req.body||{};if(body.schedule_type==='cron')nextCron(new Date(body.publish_at),body.cron_expression,body.timezone||'UTC');const data=await schedules.update({id:req.params.id,userId:req.user.id,name:body.name,channelId:body.channel_id,projectId:body.project_id,publishAt:body.publish_at,timezone:body.timezone,scheduleType:body.schedule_type,cronExpression:body.cron_expression,payload:body.payload,enabled:body.enabled});send(res,200,{success:true,data})}catch(error){send(res,400,{success:false,error:{code:'INVALID_SCHEDULE',message:error.message}})}}
export async function remove(req,res){try{const ok=await schedules.remove(req.params.id,req.user.id);if(!ok)return send(res,404,{success:false,error:{code:'NOT_FOUND',message:'Schedule not found'}});send(res,200,{success:true,data:{id:req.params.id,deleted:true}})}catch(error){send(res,500,{success:false,error:{code:'DATABASE',message:'Schedule could not be deleted'}})}}
export async function runNow(req,res){try{const schedule=await schedules.get(req.params.id,req.user.id);if(!schedule)return send(res,404,{success:false,error:{code:'NOT_FOUND',message:'Schedule not found'}});const job=await enqueue({user_id:req.user.id,channel_id:schedule.channel_id,project_id:schedule.project_id,job_type:'pipeline',current_step:'research',input:{...(schedule.payload||{}),schedule_id:schedule.id,manual_schedule_run:true},priority:4,max_retries:3});send(res,201,{success:true,data:job})}catch(error){send(res,400,{success:false,error:{code:error.code||'RUN_FAILED',message:error.message||'Schedule could not be started'}})}}
