REVOKE EXECUTE ON FUNCTION public.claim_next_job(text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.watchdog_workers() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.recover_stale_workers() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.reconcile_queue() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.reconcile_schedules() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.reconcile_system() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_artifacts() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_next_job(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.watchdog_workers() TO service_role;
GRANT EXECUTE ON FUNCTION public.recover_stale_workers() TO service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_queue() TO service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_schedules() TO service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_system() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_artifacts() TO service_role;
ALTER FUNCTION public.claim_next_job(text) SET search_path = pg_catalog, public;
ALTER FUNCTION public.watchdog_workers() SET search_path = pg_catalog, public;
ALTER FUNCTION public.recover_stale_workers() SET search_path = pg_catalog, public;
ALTER FUNCTION public.reconcile_queue() SET search_path = pg_catalog, public;
ALTER FUNCTION public.reconcile_schedules() SET search_path = pg_catalog, public;
ALTER FUNCTION public.reconcile_system() SET search_path = pg_catalog, public;
ALTER FUNCTION public.cleanup_expired_artifacts() SET search_path = pg_catalog, public;
