DROP POLICY IF EXISTS users_self ON users; CREATE POLICY users_self ON users FOR SELECT USING (id=(select auth.uid()));
DROP POLICY IF EXISTS channels_tenant ON channels; CREATE POLICY channels_tenant ON channels FOR ALL USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
DROP POLICY IF EXISTS projects_channel ON projects; CREATE POLICY projects_channel ON projects FOR ALL USING (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid()))) WITH CHECK (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid())));
DROP POLICY IF EXISTS jobs_user ON automation_jobs; CREATE POLICY jobs_user ON automation_jobs FOR ALL USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
DROP POLICY IF EXISTS artifacts_tenant ON artifacts; CREATE POLICY artifacts_tenant ON artifacts FOR ALL USING (tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid()))) WITH CHECK (tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid())));
DROP POLICY IF EXISTS schedules_channel ON schedules; CREATE POLICY schedules_channel ON schedules FOR ALL USING (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid()))) WITH CHECK (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid())));
DROP POLICY IF EXISTS analytics_channel ON analytics; CREATE POLICY analytics_channel ON analytics FOR SELECT USING (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid())));
DROP POLICY IF EXISTS tenants_self ON tenants; CREATE POLICY tenants_self ON tenants FOR SELECT USING (id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid())));
DROP POLICY IF EXISTS channel_memory_user ON channel_memory; CREATE POLICY channel_memory_user ON channel_memory FOR ALL USING (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid()))) WITH CHECK (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid())));
DROP POLICY IF EXISTS channel_memory_versions_user ON channel_memory_versions; CREATE POLICY channel_memory_versions_user ON channel_memory_versions FOR ALL USING (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid()))) WITH CHECK (channel_id IN (SELECT id FROM channels WHERE user_id=(select auth.uid())));
DROP POLICY IF EXISTS project_versions_user ON project_versions; CREATE POLICY project_versions_user ON project_versions FOR ALL USING (project_id IN (SELECT p.id FROM projects p JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid()))) WITH CHECK (project_id IN (SELECT p.id FROM projects p JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid())));
DROP POLICY IF EXISTS pipeline_runs_user ON pipeline_runs; CREATE POLICY pipeline_runs_user ON pipeline_runs FOR ALL USING (project_id IN (SELECT p.id FROM projects p JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid()))) WITH CHECK (project_id IN (SELECT p.id FROM projects p JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid())));
DROP POLICY IF EXISTS pipeline_steps_user ON pipeline_steps; CREATE POLICY pipeline_steps_user ON pipeline_steps FOR ALL USING (pipeline_run_id IN (SELECT pr.id FROM pipeline_runs pr JOIN projects p ON p.id=pr.project_id JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid()))) WITH CHECK (pipeline_run_id IN (SELECT pr.id FROM pipeline_runs pr JOIN projects p ON p.id=pr.project_id JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid())));
DROP POLICY IF EXISTS scenes_user ON scenes; CREATE POLICY scenes_user ON scenes FOR ALL USING (project_id IN (SELECT p.id FROM projects p JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid()))) WITH CHECK (project_id IN (SELECT p.id FROM projects p JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid())));
DROP POLICY IF EXISTS scene_versions_user ON scene_versions; CREATE POLICY scene_versions_user ON scene_versions FOR ALL USING (scene_id IN (SELECT s.id FROM scenes s JOIN projects p ON p.id=s.project_id JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid()))) WITH CHECK (scene_id IN (SELECT s.id FROM scenes s JOIN projects p ON p.id=s.project_id JOIN channels c ON c.id=p.channel_id WHERE c.user_id=(select auth.uid())));
DROP POLICY IF EXISTS job_items_user ON job_items; CREATE POLICY job_items_user ON job_items FOR ALL USING (job_id IN (SELECT id FROM automation_jobs WHERE user_id=(select auth.uid()))) WITH CHECK (job_id IN (SELECT id FROM automation_jobs WHERE user_id=(select auth.uid())));
DROP POLICY IF EXISTS faults_user ON faults; CREATE POLICY faults_user ON faults FOR ALL USING (tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid()))) WITH CHECK (tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid())));
DROP POLICY IF EXISTS recovery_attempts_user ON recovery_attempts; CREATE POLICY recovery_attempts_user ON recovery_attempts FOR ALL USING (fault_id IN (SELECT f.id FROM faults f WHERE f.tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid())))) WITH CHECK (fault_id IN (SELECT f.id FROM faults f WHERE f.tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid()))));
DROP POLICY IF EXISTS commands_user ON commands; CREATE POLICY commands_user ON commands FOR ALL USING (user_id=(select auth.uid())) WITH CHECK (user_id=(select auth.uid()));
DROP POLICY IF EXISTS artifact_versions_user ON artifact_versions; CREATE POLICY artifact_versions_user ON artifact_versions FOR ALL USING (artifact_id IN (SELECT a.id FROM artifacts a WHERE a.tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid())))) WITH CHECK (artifact_id IN (SELECT a.id FROM artifacts a WHERE a.tenant_id IN (SELECT tenant_id FROM users WHERE id=(select auth.uid()))));
CREATE INDEX IF NOT EXISTS users_tenant_id_idx ON users(tenant_id);
CREATE INDEX IF NOT EXISTS channels_tenant_id_idx ON channels(tenant_id);
CREATE INDEX IF NOT EXISTS channels_user_id_idx ON channels(user_id);
CREATE INDEX IF NOT EXISTS channel_memory_versions_channel_id_idx ON channel_memory_versions(channel_id);
CREATE INDEX IF NOT EXISTS projects_tenant_id_idx ON projects(tenant_id);
CREATE INDEX IF NOT EXISTS projects_channel_id_idx ON projects(channel_id);
CREATE INDEX IF NOT EXISTS project_versions_project_id_idx ON project_versions(project_id);
CREATE INDEX IF NOT EXISTS pipeline_runs_project_id_idx ON pipeline_runs(project_id);
CREATE INDEX IF NOT EXISTS pipeline_steps_pipeline_run_id_idx ON pipeline_steps(pipeline_run_id);
CREATE INDEX IF NOT EXISTS scenes_project_id_idx ON scenes(project_id);
CREATE INDEX IF NOT EXISTS scene_versions_scene_id_idx ON scene_versions(scene_id);
CREATE INDEX IF NOT EXISTS automation_jobs_tenant_id_idx ON automation_jobs(tenant_id);
CREATE INDEX IF NOT EXISTS automation_jobs_user_id_idx ON automation_jobs(user_id);
CREATE INDEX IF NOT EXISTS automation_jobs_channel_id_idx ON automation_jobs(channel_id);
CREATE INDEX IF NOT EXISTS automation_jobs_project_id_idx ON automation_jobs(project_id);
CREATE INDEX IF NOT EXISTS automation_jobs_parent_job_id_idx ON automation_jobs(parent_job_id);
CREATE INDEX IF NOT EXISTS job_items_scene_id_idx ON job_items(scene_id);
CREATE INDEX IF NOT EXISTS workers_current_job_id_idx ON workers(current_job_id);
CREATE INDEX IF NOT EXISTS worker_heartbeats_worker_id_idx ON worker_heartbeats(worker_id);
CREATE INDEX IF NOT EXISTS worker_heartbeats_job_id_idx ON worker_heartbeats(job_id);
CREATE INDEX IF NOT EXISTS faults_tenant_id_idx ON faults(tenant_id);
CREATE INDEX IF NOT EXISTS faults_channel_id_idx ON faults(channel_id);
CREATE INDEX IF NOT EXISTS faults_project_id_idx ON faults(project_id);
CREATE INDEX IF NOT EXISTS faults_job_id_idx ON faults(job_id);
CREATE INDEX IF NOT EXISTS recovery_attempts_fault_id_idx ON recovery_attempts(fault_id);
CREATE INDEX IF NOT EXISTS commands_tenant_id_idx ON commands(tenant_id);
CREATE INDEX IF NOT EXISTS commands_channel_id_idx ON commands(channel_id);
CREATE INDEX IF NOT EXISTS commands_project_id_idx ON commands(project_id);
CREATE INDEX IF NOT EXISTS commands_job_id_idx ON commands(job_id);
CREATE INDEX IF NOT EXISTS audit_logs_tenant_id_idx ON audit_logs(tenant_id);
CREATE INDEX IF NOT EXISTS audit_logs_user_id_idx ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS audit_logs_channel_id_idx ON audit_logs(channel_id);
CREATE INDEX IF NOT EXISTS audit_logs_project_id_idx ON audit_logs(project_id);
CREATE INDEX IF NOT EXISTS audit_logs_job_id_idx ON audit_logs(job_id);
CREATE INDEX IF NOT EXISTS artifacts_tenant_id_idx ON artifacts(tenant_id);
CREATE INDEX IF NOT EXISTS artifacts_project_id_idx ON artifacts(project_id);
CREATE INDEX IF NOT EXISTS schedules_tenant_id_idx ON schedules(tenant_id);
CREATE INDEX IF NOT EXISTS provider_configs_tenant_id_idx ON provider_configs(tenant_id);
CREATE INDEX IF NOT EXISTS provider_configs_channel_id_idx ON provider_configs(channel_id);
CREATE INDEX IF NOT EXISTS provider_configs_project_id_idx ON provider_configs(project_id);
CREATE INDEX IF NOT EXISTS provider_health_provider_config_id_idx ON provider_health(provider_config_id);
CREATE INDEX IF NOT EXISTS analytics_project_id_idx ON analytics(project_id);
