create table if not exists public.content_history(id uuid primary key default gen_random_uuid(),channel_id uuid not null references public.channels(id) on delete cascade,youtube_video_id text not null,title text,description text,topic text,recipe_concept text,keywords text[] not null default '{}',published_at timestamptz,duration_seconds int,content_type text not null default 'video',content_fingerprint text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(channel_id,youtube_video_id));
create index if not exists idx_content_history_channel_published on public.content_history(channel_id,published_at desc);
create index if not exists idx_content_history_channel_type on public.content_history(channel_id,content_type);
create table if not exists public.short_generations(id uuid primary key default gen_random_uuid(),channel_id uuid not null references public.channels(id) on delete cascade,project_id uuid references public.projects(id) on delete cascade,job_id uuid references public.automation_jobs(id) on delete set null,idempotency_key text not null unique,attempt int not null default 0,status text not null default 'candidate',topic text,recipe_concept text,title text,description text,hashtags text[] not null default '{}',keywords text[] not null default '{}',content_fingerprint text,payload jsonb not null default '{}',rejection_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_short_generations_channel_created on public.short_generations(channel_id,created_at desc);
insert into storage.buckets(id,name,public) values('automation-artifacts','automation-artifacts',false) on conflict (id) do nothing;
alter table public.content_history enable row level security;alter table public.short_generations enable row level security;
create policy content_history_service_access on public.content_history for all to service_role using(true) with check(true);
create policy short_generations_service_access on public.short_generations for all to service_role using(true) with check(true);
